chore: script cleanup

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,18 +1,18 @@
 #!/usr/bin/env bash
 
 command -v node >/dev/null 2>&1 || { echo >&2 "node is not installed.  Aborting."; exit 1; }
-command -v yarn >/dev/null 2>&1 || { echo >&2 "yarn is not installed.  Aborting."; exit 1; }
+command -v pnpm >/dev/null 2>&1 || { echo >&2 "pnpm is not installed.  Aborting."; exit 1; }
 
 echo "== Getting Setup =="
 
 echo ""
-echo "== Running Yarn Install =="
-yarn install
+echo "== Running NPM Install =="
+pnpm run install
 
 echo ""
 echo "== Running Documentation Install =="
 cd documentation
-yarn install
+pnpm run install
 cd ..
 
 echo ""
